server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Evita que o NGINX remova a porta original (8081) ao fazer redirecionamentos
    absolute_redirect off;

    location / {
        # Try finding the exact file, or the file with .html, or fallback to index.html
        try_files $uri $uri/ $uri.html /index.html;
    }

    # Optional: Cache static assets
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public";
    }
}
